version : 1

formatters :
    all :
        format  : "{asctime:12s} {levelname:8s} {name:20s} : {message}"
        datefmt : "%H:%M:%S"
        style   : "{"
    short :
        format  : "{levelname:8s} {name:20s} : {message}"
        style   : "{"

handlers :
    console :
        class     : logging.StreamHandler
        formatter : short
        level     : DEBUG
        stream    : ext://sys.stdout

root :
    handlers :
        - console
    level : DEBUG

disable_existing_loggers : false
